"""Middle East company career pages (batch 8)."""

MIDDLE_EAST_JOB_SOURCES = [
    {"name": "ADIB (Abu Dhabi Islamic Bank) IT", "url": "https://www.adib.ae/en/pages/careers.aspx", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Al Tayer Digital", "url": "https://www.altayer.com/careers", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Bayzat", "url": "https://app.whitecarrot.io/careers/bayzat", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "DP World IT", "url": "https://www.dpworld.com/en/careers", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Dubai Electricity and Water Authority (DEWA) IT", "url": "https://www.dewa.gov.ae/en/about-dewa/careers", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Dulsco", "url": "https://www.dulsco.com/en/careers", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Emirates Group IT", "url": "https://www.emiratesgroupcareers.com", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Etisalat Digital", "url": "https://careers.etisalat.ae", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Exec-Tech", "url": "https://exec-tech.com/positions", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "G42", "url": "https://careers.g42.ai/careers-home/jobs", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Gulf Business Machines", "url": "https://careers.gbmme.com/search", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Halian Middle East", "url": "https://www.halian.com/jobs", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "IT People Gulf", "url": "https://www.itpeoplegulf.com/life-at-it-people", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "ManpowerGroup Middle East", "url": "https://www.manpowergroup.ae/jobs/information-technology-1", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Network International", "url": "https://www.network.ae/careers", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Noon.com", "url": "https://noon.careers/", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "RTA (Roads and Transport Authority)", "url": "https://www.rta.ae/wps/portal/rta/ae/home/careers", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "TASC Outsourcing", "url": "https://tascoutsourcing.com/en", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "minds pool", "url": "https://www.minds-pool.com/careers", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "sbs", "url": "https://sbs-software.com/join-us", "region": "Middle East", "type": "company", "playwright": True},

    # Turkish tech companies (from career-ops integration)
    {"name": "Trendyol", "url": "https://www.trendyol.com/kariyerimiz", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Hepsiburada", "url": "https://www.hepsiburada.com/kariyer", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Getir", "url": "https://jobs.lever.co/getir", "region": "Middle East", "type": "company", "ats": "lever", "ats_slug": "getir"},
    {"name": "Insider", "url": "https://useinsider.com/careers", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Dream Games", "url": "https://www.dreamgames.com/careers", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Peak Games (Zynga)", "url": "https://www.peakgames.net/en/career", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Yemeksepeti (Delivery Hero)", "url": "https://www.yemeksepeti.com/kariyer", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Sahibinden.com", "url": "https://www.sahibinden.com/kariyer", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Garanti BBVA Technology", "url": "https://www.garantibbvateknoloji.com.tr/kariyer", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Akbank Tech", "url": "https://www.akbank.com/tr-tr/sayfalar/kariyer.aspx", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Turkcell", "url": "https://kariyer.turkcell.com.tr", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Iyzico (PayU)", "url": "https://iyzico.com/kariyer", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Papara", "url": "https://papara.com/kariyer", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "Craftgate", "url": "https://craftgate.io/career", "region": "Middle East", "type": "company", "playwright": True},
    {"name": "n11.com (Do\u011fu\u015f)", "url": "https://www.n11.com/kurumsal/kariyer", "region": "Middle East", "type": "company", "playwright": True},
]
