"""Remote-friendly company career pages (batch: remote).

Sources: Google Sheet Remote tab — validated Career URLs.
"""

REMOTE_JOB_SOURCES = [
    {"name": "10up", "url": "https://fueled.com/careers/#open-roles", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "AirGarage", "url": "https://www.airgarage.com/careers#open-positions", "region": "USA", "type": "company", "playwright": True},
    {"name": "Aivitex", "url": "https://iuhhoo.workwise.io/jobsuche", "region": "Germany", "type": "company", "playwright": True},
    {"name": "Anomali", "url": "https://jobs.lever.co/anomali/", "region": "USA, UK, Singapore", "type": "company", "playwright": True},
    {"name": "Applaus Studios", "url": "https://applaudo.com/en/careers/", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Artefactual", "url": "https://www.artefactual.com/job-postings", "region": "UTC-8 to UTC+2", "type": "company", "playwright": True},
    {"name": "Atlassian", "url": "https://www.atlassian.com/company/careers/all-jobs?team=Engineering&location=&search=", "region": "USA, Europe, Asia, Australia", "type": "company", "playwright": True},
    {"name": "Audiense", "url": "https://ats.rippling.com/en-GB/buxtoncocareers/jobs", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Axios", "url": "https://job-boards.greenhouse.io/axios?departments%5B%5D=151029", "region": "USA", "type": "company", "playwright": True},
    {"name": "Bazaarvoice", "url": "https://www.bazaarvoice.com/company/careers/#job-openings", "region": "USA", "type": "company", "playwright": True},
    {"name": "BetterUp", "url": "https://www.betterup.com/about-us/careers", "region": "USA", "type": "company", "playwright": True},
    {"name": "Blameless", "url": "https://ats.rippling.com/firehydrant/jobs", "region": "North America", "type": "company", "playwright": True},
    {"name": "Bounteous", "url": "https://www.bounteous.com/careers/search-results/?q=", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Brainstorm Force", "url": "https://brainstormforce.com/join/", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Cabify", "url": "https://cabify.careers/en/jobs?search=&office=&department=Engineering and https://cabify.careers/en/jobs?search=&office=&department=Information%20Technology%C2%A0", "region": "Spain, Poland", "type": "company", "playwright": True},
    {"name": "Calibre", "url": "https://calibreapp.com/careers", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "CANCOM (Germany)", "url": "https://career.cancom.com/?post_type=jobs&s=", "region": "Germany", "type": "company", "playwright": True},
    {"name": "CANCOM (Austria)", "url": "https://jobs.cancom.com/stellenangebote.html?filter%5Bcountr%5D%5B%5D=Dornbirn&filter%5Bcountr%5D%5B%5D=Graz&filter%5Bcountr%5D%5B%5D=Innsbruck&filter%5Bcountr%5D%5B%5D=Klagenfurt&filter%5Bcountr%5D%5B%5D=Leonding/Hart&filter%5Bcountr%5D%5B%5D=Raaba-Grambach&filter%5Bcountr%5D%5B%5D=Salzburg&filter%5Bcountr%5D%5B%5D=St.+P%C3%B6lten&filter%5Bcountr%5D%5B%5D=Linz&filter%5Bcountr%5D%5B%5D=Wien", "region": "Austria", "type": "company", "playwright": True},
    {"name": "Canonical", "url": "https://canonical.com/careers/all?filter=Engineering", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Capchase", "url": "https://jobs.ashbyhq.com/capchase", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Carbon Black", "url": "https://broadcom.wd1.myworkdayjobs.com/External_Career?jobFamilyGroup=5d531f3d0e8c416786d61a13b265af9e", "region": "USA", "type": "company", "playwright": True},
    {"name": "Cards Against Humanity", "url": "https://www.cardsagainsthumanity.com/careers", "region": "USA", "type": "company", "playwright": True},
    {"name": "Celsius", "url": "https://apply.workable.com/celsius/", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Chargify", "url": "https://www.maxio.com/careers#open-positions", "region": "USA", "type": "company", "playwright": True},
    {"name": "Chef", "url": "https://www.progress.com/company/careers/open-positions", "region": "USA, UK, Brazil", "type": "company", "playwright": True},
    {"name": "Circonus", "url": "https://www.apica.io/careers/#hiring", "region": "USA", "type": "company", "playwright": True},
    {"name": "CivicActions", "url": "https://civicactions.com/careers/#open-positions", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Civo", "url": "https://careers.civo.com/jobs?query=&department=Technical", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Clootrack", "url": "https://www.clootrack.com/careers", "region": "India", "type": "company", "playwright": True},
    {"name": "CloudLabs", "url": "https://cloudlabsit.com/careers/page/2/", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Coingape", "url": "https://coingape.com/careers/", "region": "India", "type": "company", "playwright": True},
    {"name": "Comet", "url": "https://www.comet.com/site/about-us/careers/#CurrentJobs", "region": "France", "type": "company", "playwright": True},
    {"name": "Continu", "url": "https://careers.continu.com/", "region": "USA", "type": "company", "playwright": True},
    {"name": "Core-Apps", "url": "https://communitybrands.wd1.myworkdayjobs.com/Momentive_External_Careers?jobFamilyGroup=4054392cf9e101d77111f6368f010204", "region": "USA", "type": "company", "playwright": True},
    {"name": "CoreOS", "url": "https://redhat.wd5.myworkdayjobs.com/jobs/?d=c18026e77576010f6ef6126f4e43ec4a&d=c18026e7757601cf6eb0136f4e43f04a", "region": "USA", "type": "company", "playwright": True},
    {"name": "CrowdStrike", "url": "https://crowdstrike.wd5.myworkdayjobs.com/crowdstrikecareers?Job_Family=1408861ee6e20197f95adbf6b000d20b&Job_Family=1408861ee6e201641be2c2f6b000c00b&Job_Family=1408861ee6e201b287b816f7b000020c", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Customer.io", "url": "https://customer.io/careers#job-openings", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "DataCamp", "url": "https://www.datacamp.com/jobs", "region": "Europe", "type": "company", "playwright": True},
    {"name": "Dev Spotlight", "url": "https://www.dice.com/company-profile/174a3aff-8d35-4025-8f71-d6311242c055", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Dgraph", "url": "https://www.dgraphtech.com/jobs", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Discourse", "url": "https://www.discourse.org/jobs", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "DNSimple", "url": "https://dnsimple.com/jobs", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "EatStreet", "url": "https://eatstreet.com/careers", "region": "USA", "type": "company", "playwright": True},
    {"name": "EBSCO", "url": "https://careers-ebscoind.icims.com/jobs/search?ss=1&searchRelation=keyword_all&searchCategory=8730", "region": "USA", "type": "company", "playwright": True},
    {"name": "Elastic", "url": "https://jobs.elastic.co/jobs/department/engineering?size=n_20_n", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Envato", "url": "https://jobs.lever.co/envato-2", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Envoy", "url": "https://envoy.com/jobs#open-jobs", "region": "USA, Canada, Colombia", "type": "company", "playwright": True},
    {"name": "Epic Games", "url": "https://www.epicgames.com/site/careers/jobs?department=Engineering%2BProduction&page=1", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Episource", "url": "https://careers.unitedhealthgroup.com/search-jobs?acm=ALL&alrpm=ALL&ascf=[%7B%22key%22:%22custom_fields.UHGAJDType%22,%22value%22:%22Optum%22%7D]", "region": "USA", "type": "company", "playwright": True},
    {"name": "Equal Experts", "url": "https://www.equalexperts.com/current-opportunities/", "region": "Europe", "type": "company", "playwright": True},
    {"name": "Etsy", "url": "https://careers.etsy.com/jobs/search?page=1&department_uids%5B%5D=9c01bdbfdf9b047d7c1077a95d88ed61&query=", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Evrone", "url": "https://hh.ru/employer/598471?tab=VACANCIES", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Fastly", "url": "https://www.fastly.com/about/careers/current-openings?department=Engineering", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Fetlife", "url": "https://fetlife.com/jobs", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Flowing", "url": "https://claranet.jobs/recruit/fRecruit__ApplyJobList", "region": "Italy", "type": "company", "playwright": True},
    {"name": "Fly.io", "url": "https://fly.io/jobs/", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "FMX", "url": "https://www.gofmx.com/careers/", "region": "USA", "type": "company", "playwright": True},
    {"name": "Focus Networks", "url": "https://www.focustsi.com/about-focus/careers/#jobs", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Formstack", "url": "https://jobs.ashbyhq.com/Intellistack?departmentId=b7afda52-f6f7-488f-a689-cde14d82b7dd", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Freeletics", "url": "https://www.freeletics.com/en/corporate/", "region": "Germany, Poland, Portugal", "type": "company", "playwright": True},
    {"name": "GFT", "url": "https://jobs.gft.com/search/?q=&q2=&alertId=&locationsearch=&title=&shifttype=&location=&date=#searchresults", "region": "Asia, Europe, Latin America, North America", "type": "company", "playwright": True},
    {"name": "Ghost Foundation", "url": "https://careers.ghost.org/", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "Ghost Inspector", "url": "https://ghostinspector.com/jobs/", "region": "North America, Latin America", "type": "company", "playwright": True},
    {"name": "GitLab", "url": "https://about.gitlab.com/jobs/all-jobs/?dept=Engineering", "region": "Worldwide", "type": "company", "playwright": True},
    {"name": "HelloBonsai", "url": "https://apply.workable.com/hellobonsai/?lng=en", "region": "Worldwide", "type": "company", "playwright": True},
]
