"""Remote-friendly company career pages (batch: remote)."""

REMOTE_JOB_SOURCES = [
    {"name": "10up", "url": "https://10up.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "42 Technologies", "url": "https://www.42technologies.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Abiturma", "url": "https://www.abiturma.de/en/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "AirGarage", "url": "https://www.airgarage.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "AirTreks", "url": "https://www.airtreks.com/jobs", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Aivitex", "url": "https://aivitex.com/en/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Anomali", "url": "https://www.anomali.com/company/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Applaus Studios", "url": "https://applaudostudios.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Appstractor", "url": "https://www.appstractor.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Artefactual", "url": "https://www.artefactual.com/jobs/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Atlassian", "url": "https://www.atlassian.com/company/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Audiense", "url": "https://www.audiense.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Aula Education", "url": "https://aula.education/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Axios", "url": "https://www.axios.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Bazaarvoice", "url": "https://www.bazaarvoice.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Best Practical Solutions", "url": "https://bestpractical.com/careers.html", "region": "Remote", "type": "company", "playwright": True},
    {"name": "BetterUp", "url": "https://www.betterup.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Blameless", "url": "https://www.blameless.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Bounteous", "url": "https://www.bounteous.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Brainstorm Force", "url": "https://brainstormforce.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Bright Funds", "url": "https://www.brightfunds.org/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Cabify", "url": "https://www.cabify.com/en/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Calibre", "url": "https://calibreapp.com/jobs", "region": "Remote", "type": "company", "playwright": True},
    {"name": "CANCOM", "url": "https://www.cancom.com/en/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Canonical", "url": "https://www.canonical.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Capchase", "url": "https://www.capchase.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Carbon Black", "url": "https://www.carbonblack.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Cards Against Humanity", "url": "https://cardsagainsthumanity.com/jobs", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Celsius", "url": "https://celsius.network/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Chargify", "url": "https://www.chargify.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "charity: water", "url": "https://www.charitywater.org/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Chef", "url": "https://www.chef.io/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Chroma", "url": "https://ichroma.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Circonus", "url": "https://circonus.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "CivicActions", "url": "https://civicactions.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Civo", "url": "https://www.civo.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Clootrack", "url": "https://www.clootrack.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "CloudLabs", "url": "https://cloudlabs.inc/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Codestunts", "url": "https://codestunts.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Coingape", "url": "https://coingape.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Comet", "url": "https://www.comet.com/jobs/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Continu", "url": "https://www.continu.co/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Conversio", "url": "https://conversio.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Core-Apps", "url": "https://www.core-apps.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "CoreOS", "url": "https://coreos.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Corgibytes", "url": "https://corgibytes.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "CrowdStrike", "url": "https://www.crowdstrike.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Customer.io", "url": "https://customer.io/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Cuvette", "url": "https://cuvette.tech/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "CWT", "url": "https://www.mycwt.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "DataCamp", "url": "https://www.datacamp.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Deskpass", "url": "https://www.deskpass.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Dev Spotlight", "url": "https://www.devspotlight.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Dgraph", "url": "https://dgraph.io/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Discourse", "url": "https://www.discourse.org/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "DNSimple", "url": "https://dnsimple.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "DynaPictures", "url": "https://dynapictures.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "EatStreet", "url": "https://eatstreet.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "EBSCO", "url": "https://www.ebsco.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Elastic", "url": "https://www.elastic.co/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Enoki", "url": "https://www.enoki.co/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Entrision", "url": "https://entrision.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Envato", "url": "https://envato.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Envoy", "url": "https://envoy.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "EPAM Systems", "url": "https://www.epam.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Epic Games", "url": "https://www.epicgames.com/site/en-US/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Epilocal", "url": "https://www.epilocal.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Episource", "url": "https://episource.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Equal Experts", "url": "https://www.equalexperts.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Etsy", "url": "https://www.etsy.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Evrone", "url": "https://evrone.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "ExportData", "url": "https://www.exportdata.io/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Fairwinds", "url": "https://www.fairwinds.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Faithlife", "url": "https://www.faithlife.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Fastly", "url": "https://www.fastly.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Fauna", "url": "https://www.fauna.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Fetlife", "url": "https://fetlife.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Featurist", "url": "https://www.featurist.co.uk/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Fireball Labs", "url": "https://www.fireballlabs.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Fiverr", "url": "https://www.fiverr.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "FlightAware", "url": "https://flightaware.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Flowing", "url": "https://flowing.it/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Fly.io", "url": "https://fly.io/jobs/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "FMX", "url": "https://www.gofmx.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Focus Networks", "url": "https://www.focusnetworks.com.br/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Formstack", "url": "https://www.formstack.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Four Kitchens", "url": "https://fourkitchens.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Freeletics", "url": "https://www.freeletics.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Functionize", "url": "https://www.functionize.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Gaggle", "url": "https://www.gaggle.net/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Geckoboard", "url": "https://www.geckoboard.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "GFT", "url": "https://www.gft.com/careers", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Ghost Foundation", "url": "https://ghost.org/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "Ghost Inspector", "url": "https://ghostinspector.com/careers/", "region": "Remote", "type": "company", "playwright": True},
    {"name": "HelloBonsai", "url": "https://www.hellobonsai.com/careers", "region": "Remote", "type": "company", "playwright": True},
]
